#!/bin/bash
#control touch pad

if [ $# != 1 ]
then
 echo "Usage: touchpad (on |off)"
elif [ $1 = "on" ]
then
 sudo modprobe psmouse
elif [ $1 = "off" ]
then
 sudo modprobe -r psmouse
else
 echo "Usage: touchpad (on |off)"
fi
